name: ecomerce_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.5.1
  http: ^1.2.2
  intl: ^0.19.0
  dio: ^5.7.0
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  path_provider: ^2.1.5
  image_gallery_saver_plus: ^3.0.5
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  lottie: ^3.1.3
  connectivity_plus: ^6.1.0
  introduction_screen: ^3.1.14
  date_field: ^5.3.0
  flutter_html: ^3.0.0-beta.2
  multi_dropdown: ^3.0.1
  contained_tab_bar_view: ^0.8.0
  carousel_slider: ^5.0.0
  syncfusion_flutter_charts: ^27.2.5
  html: ^0.15.4
  async: ^2.11.0
  font_awesome_flutter: ^10.8.0
  animated_splash_screen: ^1.3.0
  quickalert: ^1.1.0
  badges: ^3.1.2
  flutter_slidable: ^4.0.0
  google_fonts: ^6.2.1
  flutter_local_notifications: ^19.0.0

  cloud_firestore: ^5.6.4
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_storage: ^12.4.3
  firebase_database: ^11.3.3

  date_picker_timeline: ^1.2.6
  flutter_staggered_animations: ^1.1.1
  sqflite: ^2.4.1
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0

  # local_auth: ^2.1.6
  local_auth: ^2.3.0
  flutter_windowmanager_plus: ^1.0.1
  flutter_native_splash: ^2.3.13
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/icon/icon.png"
#   adaptive_icon_background: "#1E3A8A"
#   adaptive_icon_foreground: "assets/icon/icon.png"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#ffffff"
  background_image: assets/images/backg.png
  image: assets/images/backg.png
  branding: assets/images/backg.png
  # color_dark: "#121212"
  # image_dark: assets/logo/logo_1.jpg
  # branding_dark: assets/logo/logo_1.jpg

  android_12:
    image: assets/images/backg.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/backg.png
    icon_background_color_dark: "#121212"

  web: false


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - assets/langs/
    - assets/lottie/
    - assets/sound/
    - assets/shoe/
    - assets/icon/
    - assets/images/black_bg.png

  fonts:
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/fonts/Montserrat-Arabic-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Arabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Arabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Arabic-Bold.ttf
          weight: 700
